name: JavaScript App CI/CD
on:
  workflow_dispatch:
jobs:
  checkout:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dependencies
        run: |
          npm install 
      - name: lint
        run: |
          npm run eslint
    
